AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'
    - 'db/migrate/20251010175058_add_service_name_to_active_storage_blobs.active_storage.rb'

Style:
  Enabled: false

Layout:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 50
